# Generated by Django 3.2.4 on 2021-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
